CREATE DATABASE BANK_CUSTOMERS_Disseration_Project_DB

CREATE TABLE PERSONAL_DETAILS (
ID_Number INT PRIMARY KEY IDENTITY(1,1),
First_Name VARCHAR(50),
Second_Name VARCHAR(50),
Gender VARCHAR(15),
Date_of_Birth NVARCHAR(50),
Place_of_Birth NVARCHAR(50),
Nationality VARCHAR(50),
Merital_Status VARCHAR(50),
Name_of_Spouse VARCHAR(50),
Proffesion VARCHAR(50),
Mobile_Number_Code NVARCHAR(10),
Mobile_Number int,
IDCard_Number NVARCHAR(50),
Country_Name VARCHAR(50),
Province VARCHAR(50),
Town VARCHAR(50),
Township VARCHAR(50),
Quarter VARCHAR(50),
Avenue VARCHAR(50),
House_Number int,
Picture IMAGE,
);



--APPLICANT_DETAILS Table--
CREATE TABLE APPLICANT_DETAILS (
ID_Number INT PRIMARY KEY IDENTITY(1,1),
Identifier VARCHAR(50),
First_Name VARCHAR(50),
Second_Name VARCHAR(50),
Gender VARCHAR(15),
Date_of_Birth NVARCHAR(50),
Place_of_Birth NVARCHAR(50),
Nationality VARCHAR(50),
Merital_Status VARCHAR(50),
Name_of_Spouse VARCHAR(50),
Proffesion VARCHAR(50),
Mobile_Number_Code NVARCHAR(10),
Mobile_Number int,
IDCard_Number NVARCHAR(50),
Consideration VARCHAR(50),
Country_Name VARCHAR(50),
Province VARCHAR(50),
Town VARCHAR(50),
Township VARCHAR(50),
Quarter VARCHAR(50),
Avenue VARCHAR(50),
House_Number int,
Picture IMAGE,
);



--BANK_ACCOUNT_DETAILS Table--
CREATE TABLE BANK_ACCOUNT_DETAILS (
ID_Number INT PRIMARY KEY IDENTITY(202002300,1),
Date_of_creation NVARCHAR(50),
Identifier VARCHAR(50),
Bank_Account_Type VARCHAR(50),
Limit_Date NVARCHAR(50),
);



--DEPOSIT_TRANSACTION Table--
CREATE TABLE DEPOSIT_TRANSACTION(
ID_Number INT PRIMARY KEY IDENTITY(1,1),
Account_Name VARCHAR(50),
Account_Number INT,
Deposer_Name VARCHAR(50),
Transaction_Date NVARCHAR(50),
Transaction_Time NVARCHAR(50),
Amount FLOAT,
Amount_In_Words VARCHAR(100),
Currency VARCHAR(50),
Narration VARCHAR(100),
);



--WITHDRAWAL_TRANSACTION Table--
CREATE TABLE WITHDRAWAL_TRANSACTION (
ID_Number INT PRIMARY KEY IDENTITY(1,1),
Account_Name VARCHAR(50),
Account_Number INT,
Withdrawal_by VARCHAR(50),
Transaction_Date NVARCHAR(50),
Transaction_Time NVARCHAR(50),
Amount FLOAT,
Amount_In_Words VARCHAR(50),
Currency VARCHAR(15),
Narration VARCHAR(100),
);


--LOAN_TRANSACTION Table--
CREATE TABLE LOAN_TRANSACTION (
ID_Number INT PRIMARY KEY IDENTITY(1,1),
Loan_Date NVARCHAR(50),
Borrower VARCHAR(50),
Account_Number INT,
Amount FLOAT,
Amount_In_Words VARCHAR(50),
Currency VARCHAR(15),
Purpose VARCHAR(100),
Schedule NVARCHAR(100),
Limit_Date NVARCHAR(50),
Transaction_Time NVARCHAR(50),
);


--REPAYMENT_TRANSACTION Table--
CREATE TABLE REPAYMENT_TRANSACTION (
ID_Number INT PRIMARY KEY IDENTITY(1,1),
Loan_Date NVARCHAR(50),
Borrower VARCHAR(50),
Account_Number INT,
Amount FLOAT,
Amount_In_Words VARCHAR(50),
Remaining_Time NVARCHAR(50),
Transaction_Time NVARCHAR(50)

);


--ADMINISTRATOR_DETAILS Table--
CREATE TABLE ADMINISTRATOR_DETAILS (
ID_Number INT PRIMARY KEY IDENTITY(1,1),
First_Name VARCHAR(50),
Second_Name VARCHAR(50),
Fonction VARCHAR(50),
Gender VARCHAR(15),
Date_of_Birth NVARCHAR(50),
Nationality VARCHAR(50),
E_mail NVARCHAR(50),
User_Name VARCHAR(50),
Password NVARCHAR(50),
Picture IMAGE
);



--MESSAGE_COMMUNICATION Table--
CREATE TABLE MESSAGE_COMMUNICATION (
ID_Number INT PRIMARY KEY IDENTITY(1,1),
Account_Number INT,
Mobile_Number NVARCHAR(50),
Message NVARCHAR(1000),
);

--DROP TABLE PERSONAL_DETAILS
--DROP TABLE APPLICANT_DETAILS
--DROP TABLE BANK_ACCOUNT_DETAILS

--DROP TABLE DEPOSIT_TRANSACTION
--DROP TABLE WITHDRAWAL_TRANSACTION
--DROP TABLE LOAN_TRANSACTION
--DROP TABLE REPAYMENT_TRANSACTION

--DROP TABLE ADMINISTRATOR_DETAILS
--DROP TABLE MESSAGE_COMMUNICATION

SELECT * FROM PERSONAL_DETAILS
SELECT * FROM APPLICANT_DETAILS
SELECT * FROM BANK_ACCOUNT_DETAILS

SELECT * FROM DEPOSIT_TRANSACTION
SELECT * FROM WITHDRAWAL_TRANSACTION
SELECT * FROM LOAN_TRANSACTION
SELECT * FROM REPAYMENT_TRANSACTION

SELECT * FROM ADMINISTRATOR_DETAILS
SELECT * FROM MESSAGE_COMMUNICATION